LaPaNu4/project-Tenth_Team

src/images/icons.svg
=> add to icons.svg

src/partials/rating.html
=> add reting.html

src/css/weekly-trends.css, src/js/weekly-trends.js, src/partials/weekly-trends.html
=> add files weekly-trends

package-lock.json, package.json, src/css/library.css, src/css/styles.css, src/images/chevron-down.svg, src/index.js, src/js/library-filter.js, src/library.html, src/partials/library.html
=> add library section

src/css/footer.css, src/js/footer-modal.js, src/partials/footer-modal.html, src/partials/footer.html
Started work with the footer (html, js and css)
=> Started work with the footer

src/css/footer.css, src/js/footer-modal.js, src/partials/footer-modal.html, src/partials/footer.html
=> Footer positioning

src/css/header.css, src/js/header.js, src/js/light-theme.js
Исправил ошибку с current page и дофиксил колор мод кнопку(созванивался с ларисой, соглосовал с ней то что изменил )
=> header_bug_fix

src/js/rating.js
=> add rating js

src/css/footer.css, src/index.html, src/index.js, src/js/footer-modal.js, src/partials/footer-modal.html
=> Connected footer-modal

src/css/weekly-trends.css, src/js/weekly-trends.js, src/partials/weekly-trends.html
=> add weekly-trends js

src/css/weekly-trends.css
=> fix scroll

src/css/weekly-trends.css, src/js/weekly-trends.js
=> add html rating for weekly

src/css/footer.css, src/js/footer-modal.js
=> Added no-scroll

src/css/footer.css, src/partials/footer-modal.html
Added class="team-member-title"
=> Added class="team-member-title"

src/css/footer.css, src/partials/footer-modal.html
Added card-thumb into the footer-modal
=> Added card-thumb into the footer-modal

src/css/weekly-trends.css, src/js/weekly-trends.js, src/partials/weekly-trends.html
=> fix mobile

src/css/footer.css, src/css/styles.css, src/partials/footer.html
=> Footer to bottom

src/js/hero-random-film.js
=> hero-close-video

src/css/footer.css, src/partials/footer-modal.html
=> Working with cards

src/catalog.html, src/css/footer.css, src/index.html, src/library.html, src/partials/footer-modal.html, src/partials/footer.html
=> Footer modal

src/css/header.css, src/js/header.js, src/partials/header.html
додав функцію відключення скролу
=> scroll_fix
